<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptimisticTodoSample\OptimisticTodoSample.csproj" />
  </ItemGroup>

</Project>
