<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Coyote" />
    <PackageReference Include="Microsoft.Coyote.Test" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xRetry.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MemoizR\MemoizR.csproj" />
    <ProjectReference Include="..\MemoizR.Reactive\MemoizR.Reactive.csproj" />
    <ProjectReference Include="..\MemoizR.StructuredConcurrency\MemoizR.StructuredConcurrency.csproj" />
  </ItemGroup>

</Project>
